# Generated by Django 5.2 on 2026-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='init', max_length=20),
        ),
    ]
